### ISSUE TITLE
Advanced Options

### ISSUE THREAD

**Issue by xargon666** [odest/iClock#1]
Enabling this setting doesn't seem to do anything at all.

I have installed this app on a Windows 10 system.

**Comment by odest** [comment]
*I apologize for the delay in responding to your message.*

Activating **Advanced Options** at this stage only allows you to change 3 additional features: 
- Border Opacity
- Set Icons Normal Color
- Set Icons Hover Color
- 
Since this project is still new, more features will be added over time.

Thank you.
